#!/usr/bin/env python

import json
from storageclient import CleversafeClient, errors
import unittest


class TestStorage(unittest.TestCase):
    @classmethod
    def setUpClass(self):
        with open ('cred.json', 'r') as f:
            creds = json.load(f)
            new_creds = {  
                "username" : creds["username"],
                "password" : creds["password"],
                "aws_access_key_id": creds["aws_access_key_id"],
                "aws_secret_access_key": creds["aws_secret_access_key"],
                "host": creds["host"],
                "public_host": creds["public_host"],
                "port": creds["port"]
            }    
        self.cc = CleversafeClient(new_creds)

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def test_list_buckets_success(self):
        """
        Successful listing of buckets
        We test it by checking that
        at least the two test buckets we created are
        in the list
        """
        buckets = self.cc.list_buckets()
        self.assertGreaterEqual(len(buckets), 2)
        self.assertNotEqual(buckets[0],id, None)
        self.assertNotEqual(buckets[0].name, None)
                
    def test_list_users_success(self):
        """
        Sucessful listing of users
        We test it by checking that 
        there are user objects in the list,
        at least the two that we have created
        """
        users = self.cc.list_users()
        self.assertGreaterEqual(len(users), 2)
        self.assertNotEqual(users[0],id, None)
        self.assertNotEqual(users[0].username, None)
        self.assertNotEqual(users[0].keys, None)

    def test_create_user_success(self):
        """
        Used once to create the user
        to be used in the other tests
        We don't want to keep cycling through
        the autogenerated numbers
        """
        #self.cc.get_or_create_user('storage_test_user')
        self.skipTest('This test should not be enabled unless a new user is required')

    def test_delete_user_success(self):
        """
        Used once to delete users
        and check that it works,
        but we shouldn't be deleting users
        that we will need to test, or we run the risk
        of going through all the auto generated numbers
        """
        self.skipTest('This test should not be enabled unless we perform changes on this function')

    def test_create_and_delete_keypair_success(self):
        """
        Successful creation and deletion of keys
        Check that the creation and deletion of
        keys work. We check that we keep the same
        status that we got at the start
        """
        user = self.cc.get_user('storage_test_user')
        original_keys = user.keys
        keypair = self.cc.create_keypair(user.username)
        user = self.cc.get_user('storage_test_user')
        self.assertIn(keypair, user.keys)
        keys = self.cc.delete_keypair(user.username, keypair['access_key'])
        user = self.cc.get_user('storage_test_user')
        self.assertEqual(user.keys, original_keys) 
        

    def test_delete_keypair_inexistent_key(self):
        """
        Error handling of inexistent user
        """
        with self.assertRaises(errors.RequestError):
            self.cc.delete_keypair('storage_test_user', 'inexistent_key')

    def test_set_bucket_quota_succes(self):
        """
        Successful change of quota
        """
        bucket = self.cc.get_bucket('teststoragebucket')
        old_quota = bucket.quota
        if old_quota != None:
            MiB = old_quota/1048576
        else:
            MiB = 1
        self.cc.set_bucket_quota('teststoragebucket', 'MiB', 2*MiB)
        bucket = self.cc.get_bucket('teststoragebucket')
        self.assertEqual(bucket.quota/1048576, MiB*2)
        if old_quota == None:
            self.cc.set_bucket_quota('teststoragebucket', 'MiB', 0)
        else:
            self.cc.set_bucket_quota('teststoragebucket', 'MiB',  MiB)
        bucket = self.cc.get_bucket('teststoragebucket')
        self.assertEqual(bucket.quota, old_quota)
        
    def test_delete_all_keypairs_success(self):
        """
        Successful deletion of all keypairs
        """
        user = self.cc.get_user('storage_test_user')
        original_keys = user.keys
        keypair_1 = self.cc.create_keypair(user.username)
        keypair_2 = self.cc.create_keypair(user.username)
        user = self.cc.get_user('storage_test_user')
        self.assertIn(keypair_1, user.keys)
        self.assertIn(keypair_2, user.keys)
        keys = self.cc.delete_all_keypairs(user.username)
        user = self.cc.get_user('storage_test_user')
        self.assertEqual(user.keys, []) 

    def test_edit_bucket_template_success(self):
        """
        Successful modification of a template
        This method has no way of knowing if the
        data on the template has changed,
        so once checked once that it works,
        it is here only to check that we haven't
        broken the template
        """
        self.cc.edit_bucket_template(1, description="This is a test description")
        self.cc.edit_bucket_template(1, description="")

    def test_delete_user_inexistent_user(self):
        """
        Error handling of deletion of an inexistent user
        """
        with self.assertRaises(KeyError):
            self.cc.delete_user("this_user_will_never_exist")

    def test_add_bucket_acl_user_not_found_error(self):
        """
        Error handling of adding a bucket ACL on an inexistent user
        """
        with self.assertRaises(errors.NotFoundError):
            self.cc.add_bucket_acl("teststoragebucket", "non_existent_user", ['read-storage'])

    def test_add_bucket_acl_bucket_not_found_error(self):
        """
        Error handling on adding a bucket ACL on an inexistent bucket
        """
        with self.assertRaises(errors.NotFoundError):
            self.cc.add_bucket_acl("non_existent_bucket", "test_storage_user", ['read-storage'])

    def test_add_bucket_acl_success(self):
        """
        Successful addition of an ACL on a bucket
        This method has no way of retrieving the information
        TODO add writing test on the bucket to check permissions
        """
        self.cc.add_bucket_acl('teststoragebucket', 'storage_test_user',['read-storage'])
        self.cc.add_bucket_acl('teststoragebucket', 'storage_test_user',['disabled'])

    def test_get_bucket_success(self):
        """
        Successful retrieval of a bucket
        """
        bucket = self.cc.get_bucket('teststoragebucket')
        self.assertEqual(bucket.name, 'teststoragebucket')
        self.assertEqual(bucket.id, 7)
        self.assertEqual(bucket.quota, 2097152)

    def test_get_bucket_response_error(self):
        """
        Error handling on getting an inexistent bucket
        """
        with self.assertRaises(errors.RequestError):
            self.cc.get_bucket("inexistent_bucket")

    def test_update_bucket_acl_success(self):
        """
        Successful updating of a bucket ACL
        This method has no way of retrieving the modified
        information
        TODO add a writing check
        """
        self.cc.update_bucket_acl('teststoragebucket', [('storage_test_user',['read-storage'])])
        self.cc.update_bucket_acl('teststoragebucket', [('storage_test_user',['disabled'])])
