---
language: python

python:
  - "2.7"
  - "3.6"

matrix:
  allow_failures:
    - python: "2.7"

sudo: false

cache: pip

install:
  - pip install --upgrade setuptools
  - pip install -r requirements.txt
  - python setup.py install
  - pip install -r dev-requirements.txt

before_script:
  - sudo rm -f /etc/boto.cfg

script:
  - pytest -vv test
