language: python
python: 2.7
install:
   - pip install -r requirements.txt
   - python setup.py install
   - pip install -r dev-requirements.txt
script:
   - nosetests -v test/test_cleversafe_api_client.py
   - pytest test/test_google_api_client.py -vv
